FROM node:22-alpine
WORKDIR /usr/src/app
# Dependências do sistema para Prisma/Node
RUN apk add --no-cache libc6-compat openssl
# Copia apenas package.json para instalar libs
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate
EXPOSE 3333
CMD ["npm", "run", "dev"]