// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

// 1. Extração e Validação Explícita (Guard Clause)
const databaseUrl = process.env['DATABASE_URL']

if (!databaseUrl) {
  throw new Error("ERRO CRÍTICO: A variável de ambiente 'DATABASE_URL' não está definida no .env")
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
})
